### ISSUE TITLE
IllegalArgumentException: URI is not absolute after upgraded to micro-infra-spring 0.8.1

### ISSUE THREAD

**Issue by szpak** [4finance/boot-microservice-gui#5]
After upgraded to [micro-infra-spring 0.8.1](https://github.com/4finance/boot-microservice-gui/tree/topic/micro081) `AcceptanceSpec."should find a place by verifying tweet's coordinates"` test started failing with: `IllegalArgumentException: URI is not absolute`. After a brief debugging It seems that a `/` character is added in front of `http://...`.

@nurkiewicz Is it a problem you mentioned today's morning? Did you work out a quick fix for it?

The problem occurs with and without GPars (below a stacktrace with GPars disabled):
```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalArgumentException: URI is not absolute
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:879)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:649)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:144)
	at com.ofg.twitter.places.AcceptanceSpec.should find a place by verifying tweet's coordinates(AcceptanceSpec.groovy:60)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.springframework.http.client.SimpleClientHttpRequestFactory.createRequest(SimpleClientHttpRequestFactory.java:137)
	at org.springframework.http.client.BufferingClientHttpRequestFactory.createRequest(BufferingClientHttpRequestFactory.java:41)
	at org.springframework.http.client.AbstractClientHttpRequestFactoryWrapper.createRequest(AbstractClientHttpRequestFactoryWrapper.java:53)
	at org.springframework.http.client.support.HttpAccessor.createRequest(HttpAccessor.java:76)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:564)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.ofg.infrastructure.web.resttemplate.MetricsAspect.measureRestCallDuration_closure1(MetricsAspect.groovy:32)
	at com.codahale.metrics.Timer.time(Timer.java:99)
	at com.ofg.infrastructure.web.resttemplate.MetricsAspect.measureRestCallDuration(MetricsAspect.groovy:30)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:97)
	at com.ofg.infrastructure.web.correlationid.CorrelationIdAspect.wrapWithCorrelationIdForRestOperations(CorrelationIdAspect.groovy:82)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.urlTemplateExchange_closure1(RestExecutor.groovy:67)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.urlTemplateExchange_closure1(RestExecutor.groovy)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3_closure4(RestExecutor.groovy:86)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3_closure4(RestExecutor.groovy)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at com.ofg.infrastructure.correlationid.CorrelationIdUpdater.withId(CorrelationIdUpdater.groovy:42)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3(RestExecutor.groovy:85)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry_closure3(RestExecutor.groovy)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:417)
	at com.nurkiewicz.asyncretry.SyncRetryExecutor.getWithRetry(SyncRetryExecutor.java:37)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.withRetry(RestExecutor.groovy:84)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.urlTemplateExchange(RestExecutor.groovy:61)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.exchangeInternal(RestExecutor.groovy:49)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.RestExecutor.exchange(RestExecutor.groovy:34)
	at com.ofg.infrastructure.web.resttemplate.fluent.common.response.executor.ResponseTypeRelatedRequestsExecutor.exchange(ResponseTypeRelatedRequestsExecutor.groovy:41)
	at com.ofg.infrastructure.web.resttemplate.fluent.get.GetMethodBuilder$1.ofType(GetMethodBuilder.groovy:53)
	at com.ofg.twitter.controller.place.extractor.WeatherClient.findCity(WeatherClient.groovy:19)
	at com.ofg.twitter.controller.place.extractor.CityFinder.findCityFromCoordinates(CityFinder.groovy:17)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:317)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:350)
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:299)
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653)
	at com.ofg.twitter.controller.place.extractor.CoordinatesSectionExtractor.extractPlaceFrom(CoordinatesSectionExtractor.groovy:27)
	at com.ofg.twitter.controller.place.extractor.PlacesExtractor.extractPlace(PlacesExtractor.groovy:38)
	at com.ofg.twitter.controller.place.extractor.PlacesExtractor.appendExtractedTweet(PlacesExtractor.groovy:33)
	at com.ofg.twitter.controller.place.extractor.PlacesExtractor.extractPlacesFrom_closure1(PlacesExtractor.groovy:27)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at com.ofg.twitter.controller.place.extractor.PlacesExtractor.extractPlacesFrom(PlacesExtractor.groovy:27)
	at com.ofg.twitter.controller.place.extractor.PlacePropagatingWorker.collectAndPropagate(PlacePropagatingWorker.groovy:26)
	at com.ofg.twitter.controller.PairIdController.getPlacesFromTweets(PairIdController.groovy:40)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:717)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.ofg.infrastructure.web.correlationid.CorrelationIdAspect.wrapWithCorrelationId(CorrelationIdAspect.groovy:65)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
(...)
```

**Comment by nurkiewicz** [comment]
As a quick workaround, replace [this line](https://github.com/4finance/boot-microservice-gui/blob/161d5ff03605a0c7cb162990334c3f848d0ed711/src/main/groovy/com/ofg/twitter/controller/place/extractor/WeatherClient.groovy#L21) with:

    .onUrl(cityFindingServiceUrl + "?lat=${latitude}&lon=${longitude}")

**Comment by szpak** [comment]
Thanks Tomek.

**Comment by mchmielarz** [comment]
It seems the project is compatible with micro-infra-spring v0.8.7. Checked with [boot-microsevice-gui branch](https://github.com/4finance/boot-microservice/tree/boot-microservice-gui).
